### PR TITLE
Python cleanup and new example

### PR DESCRIPTION
**Pull request by giadarol**
- Removed obsolete python files
- Test data generated with pysixtracklib. Status:
   - simple beam-beam (fodo + BB) --> OK
   - LHC with beam-beam  --> OK
   - LHC without beam-beam --> NOT OK!!! (when regenerating the test data the test is not passed, to be investigated)
- Added example with complete workflow from sixtrack input to tracking (footprint from full LHC lattice with 4D and 6D beam-beam)

### CODE REVIEW

**Comment by rdemaria** [comment]
why there is an `examples/python/__init__.py`?

**Comment by giadarol** [comment]
> why there is an `examples/python/__init__.py`?

Removed now

**Comment by rdemaria** [comment]
Can you test with the new sixtracktools?

**Comment by giadarol** [comment]
I am on it

**Comment by giadarol** [comment]
All good in sixtracklib and pysixtrack :-)

image

**Pull request merged**
